server {

    # Listens on IPv4 & becomes the default server for unmatched requests
    listen 80 default_server;

    # Listens on IPv6 & becomes the default server for unmatched requests
    listen [::]:80 default_server;
    
    # Nome do servidor
    server_name gateway;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://api-loja:8080;
        # Sem / no final pois faz com que o caminho ("/") também seja passado para o servidor que receberá

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /auth/ {
        proxy_pass http://api-autenticacao:8081;
    }

    location /usuarios/ {
        proxy_pass http://api-autenticacao:8081;
    }

    # a url "/usuarios" (pra buscar todos os usuarios) não da match na location /usuarios/
    location = /usuarios {
        proxy_pass http://api-autenticacao:8081;
    }

    location /carrinhos/ {
        proxy_pass http://api-carrinho:3000;
    }

    location / {
        return 404;
    }

    # location /topicos {
    #     proxy_pass http://app-forum-api:8080/topicos;
    # }

    # location ~ /topicos/([0-9]+)$ {
    #     proxy_pass http://app-forum-api:8080/topicos/$1;
    # }
    
    # location /auth {
    #     proxy_pass http://app-forum-api:8080/auth;
    # }

    # location /info {
    #     proxy_pass http://app-forum-api:8080/actuator/info;
    # }
    
    # location /metrics {
    #     proxy_pass http://app-forum-api:8080/actuator/prometheus;
    # }
    
    # location /health {
    #     proxy_pass http://app-forum-api:8080/actuator/health;
    # }
}