apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: cntnr-api-gateway
        image: jp9910/nginx-gateway-microsservicos:main
        ports:
        # specifies which port inside the container is intended to receive traffic. 
        # However, it is primarily informational and does not actually expose the port by itself.
        - containerPort: 80 # (porta do nginx)
