apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-eureka
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: ms-autenticacao
  type: LoadBalancer

# Com o loadbalancer iniciado, pode-se usar um tunnel para acessar a aplicação para quem o loadbalancer
# faz o balanceamento, por meio do comando `minikube tunnel --bind-address=<ipDaMaquinaLocal>`