apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-autenticacao
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: ms-autenticacao
  type: LoadBalancer

# Com o loadbalancer iniciado, pode-se usar um tunnel para acessar a aplicação para quem o loadbalancer
# faz o balanceamento, por meio do comando `minikube tunnel --bind-address=<ipDaMaquinaLocal>`
---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-loja
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: ms-loja
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-memcached
spec:
  ports:
  - port: 11211
    targetPort: 11211
  selector:
    app: memcached
  type: LoadBalancer


---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-grafana
spec:
  ports:
  - port: 9091
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
