apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-ms-autenticacao
data:
  SPRING_ACTIVE_PROFILE: prod
  SPRING_DATASOURCE_URL: "jdbc:postgresql://svc-postgres-autenticacao:5432/autenticacao"
  URL_LOKI: http://svc-loki:3100
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-autenticacao
  labels:
    app: ms-autenticacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-autenticacao
  template:
    metadata:
      labels:
        app: ms-autenticacao
    spec:
      containers:
      - name: ms-autenticacao
        image: jp9910/microsservico-autenticacao:main
        ports:
        - containerPort: 8081 # specifies which port inside the container is intended to receive traffic. However, it is primarily informational and does not actually expose the port by itself.
        envFrom:
          - configMapRef:
              name: configmap-ms-autenticacao
        env:
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: configmap-postgres-autenticacao
                key: USUARIO_POSTGRES
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: senhas
                key: SENHA_POSTGRES_AUTENTICACAO
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: configmap-postgres-autenticacao
                key: NOME_DATABASE_PADRAO
          - name: SENHA_ASSINATURA_JWT
            valueFrom:
              secretKeyRef:
                name: senhas
                key: SENHA_ASSINATURA_JWT_AUTENTICACAO
