apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-postgres-autenticacao
data:
  NOME_DATABASE_PADRAO: autenticacao
  USUARIO_POSTGRES: postgres
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-autenticacao
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  # >Se o storageClassName não for definido, será usado o storage class padrão (acho que se chama standard)
  # storageClassName: standard
  
  # >Utilizando o csi-hostpath-sc como a storage class name, temos todas as vantagens de utilizar uma interface
  # >única para armazenamento, independente de ambiente;
  # minikube addons enable csi-hostpath-driver
  # storageClassName: csi-hostpath-sc
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss-postgres-autenticacao
spec:
  selector:
    matchLabels:
      app: postgres-autenticacao
  serviceName: svc-postgres-autenticacao
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: postgres-autenticacao
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: cntnr-postgres-autenticacao
          image: postgres:17
          ports:
            - containerPort: 5432
              name: port-postgres
          volumeMounts:
            - name: postgres-pv
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap-postgres-autenticacao
                  key: USUARIO_POSTGRES
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: senhas
                  key: SENHA_POSTGRES_AUTENTICACAO
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap-postgres-autenticacao
                  key: NOME_DATABASE_PADRAO
          # envFrom:
          #   - configMapRef:
          #       name: configmap-postgres-autenticacao
      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: pvc-postgres-autenticacao
